name: mall
services:
  mysql:
    image: mysql
    restart: always #崩溃后自动重启
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ali12345678
    ports:
      - "3307:3306"
    volumes:
      - ./.mysql-data:/var/lib/mysql #将数据目录挂载到本地目录以进行持久化   - ./.mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d #启动脚本               - ./db:/docker-entrypoint-initdb.d
    networks:
      - mallnetwork
  redis:
    image: redis
    restart: always
    container_name: redis
    environment:
      - REDIS_PASSWORD=123456
    ports:
      - "6379:6379"
    volumes:
      - ./.redis-data:/data
    networks:
      - mallnetwork
  rabbit:
    image: rabbitmq:3.8-management
    restart: always
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./.rabbit-data:/var/lib/rabbitmq
    networks:
      - mallnetwork
  mall-admin:
    container_name: mall-admin
    build:
      context: ./mall-admin
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - mallnetwork
  mall-portal:
    container_name: mall-portal
    build:
      context: ./mall-portal
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - mallnetwork
networks:
  mallnetwork: